accounts/urls.py
from django.urls import path, include
from accounts import views

urlpatterns = [
    path("", include('django.contrib.auth.urls')),
    path('signup/', views.SignUpView.as_view(), name='signup')
]

project_SZP/urls.py
from django.contrib import admin
from django.urls import path, include

from SZP import views

urlpatterns = [
    path("", views.IndexView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path("all/", views.MachinesListView.as_view(), name='machines'),
    path("create/", views.CreateMachineView.as_view(), name='create_machine'),
    path("delete/<int:pk>/", views.DeleteMachineView.as_view(), name='delete_machine'),
    path("update/<int:pk>/", views.UpdateMachineView.as_view(), name='update_machine'),
    path("accounts/", include('accounts.urls')),
]

SZP/models.py
from django.contrib.auth.models import User, Group
from django.db import models

# Create your models here.



class Employee(models.Model):
    position = models.CharField(max_length=64)
    vacations_start = models.DateField(null=True, blank=True)
    vacations_end = models.DateField(null=True, blank=True)
    sick_leave = models.BooleanField(default=False)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.position}, {self.vacations_start}, {self.vacations_end}, {self.sick_leave}. {self.user}"

class Tank(models.Model):
    NOT_DEFINED = -1
    TANK_CHOICES = [
        (0, 'hydroakumulator'),
        (1, 'akumulator tłokowy'),
    ]
    capacity = models.IntegerField()
    type = models.IntegerField(choices=TANK_CHOICES, default=NOT_DEFINED)
    max_pressure = models.IntegerField()
    work_pressure = models.IntegerField()
    valve_setting_pressure = models.IntegerField()
    serial_number = models.CharField(max_length=128)
    UDT_number = models.CharField(max_length=128)
    UDT_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return f"{self.capacity}, {self.type}, {self.max_pressure}, {self.work_pressure}, {self.valve_setting_pressure}, {self.serial_number}, {self.UDT_number}, {self.UDT_date}"

class Machines(models.Model):
    MT_NOT_DEFINED = -1
    MACHINE_CHOICES = [
        (0, 'odlewnicza'),
        (1, 'wózek widłowy'),
        (2, 'CNC'),
    ]
    OC_NOT_DEFINED = -1
    ORIENTATION_CHOICES = [
        (0, 'horyzontalna'),
        (1, 'wertykalna'),
    ]
    name = models.CharField(max_length=128)
    vendor = models.CharField(max_length=128)
    serial_number = models.CharField(max_length=128)
    power_consumption = models.IntegerField()
    type = models.IntegerField(choices=MACHINE_CHOICES, default=MT_NOT_DEFINED)
    orientation = models.IntegerField(choices=ORIENTATION_CHOICES, default=OC_NOT_DEFINED)
    pressure = models.IntegerField()
    pressure_tank = models.IntegerField()
    technological_schema = models.BooleanField(default=True)
    tank = models.ForeignKey(Tank, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f"{self.name}, {self.vendor}, {self.serial_number}, {self.power_consumption}, {self.type}, {self.orientation}, {self.pressure}, {self.pressure_tank}, {self.technological_schema}, {self.tank}"

class Furnace(models.Model):
    NOT_DEFINED = -1
    PS_CHOICES = [
        (0, 'gaz'),
        (1, 'prąd'),
    ]
    capacity = models.IntegerField()
    power_source = models.IntegerField(choices=PS_CHOICES, default=NOT_DEFINED)
    machine = models.OneToOneField(Machines, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f"{self.capacity}, {self.power_source}, {self.machine}"

class CastingMold(models.Model):
    index = models.CharField(max_length=128)
    owner = models.CharField(max_length=128)
    tool_shop = models.CharField(max_length=128)
    machines = models.ManyToManyField(Machines, through="TechSchema")

    def __str__(self):
        return f"{self.index}, {self.owner}, {self.tool_shop}, {self.machines}"

class TechSchema(models.Model):
    NOT_DEFINED = -1
    ALLOY_CHOICES = [
        (0, '226'),
        (1, '231'),
        (2, '230'),
        (3, 'ZL5'),
    ]
    machine = models.ForeignKey(Machines, on_delete=models.CASCADE, null=True)
    casting_mold = models.ForeignKey(CastingMold, on_delete=models.CASCADE, null=True)
    detail_name = models.CharField(max_length=128)
    alloy_type = models.IntegerField(choices=ALLOY_CHOICES, default=NOT_DEFINED)
    pdf_file = models.FileField(upload_to='uploads/%Y/%m/%d/')

    def __str__(self):
        return f"{self.machine}, {self.casting_mold}, {self.detail_name}, {self.alloy_type}, {self.pdf_file}"

SZP/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render

# Create your views here.
from django.views import View
from django.views.generic import ListView, UpdateView, CreateView, DeleteView
from django_tables2 import SingleTableView

from SZP.models import Machines, Employee
from django.urls import reverse_lazy

from SZP.permission_mixin import MyTestUserPassesTest


class IndexView(View):
    def get(self, request):
        return render(request, 'base.html')

class MachinesListView(LoginRequiredMixin, SingleTableView):
    model = Machines
    template_name = 'machine_list_view.html'

class CreateMachineView(LoginRequiredMixin, CreateView):
    model = Machines
    template_name = 'form.html'
    fields = ['name', 'vendor', 'serial_number', 'power_consumption', 'type', 'orientation', 'pressure', 'pressure_tank', 'tank']
    success_url = reverse_lazy('machines')


class UpdateMachineView(LoginRequiredMixin, UpdateView):
    model = Machines
    template_name = 'form.html'
    fields = ['name', 'vendor', 'serial_number', 'power_consumption', 'type', 'orientation', 'pressure', 'pressure_tank', 'tank']
    success_url = reverse_lazy('machines')

class DeleteMachineView(LoginRequiredMixin, DeleteView):
    model = Machines
    template_name = 'delete.html'
    success_url = reverse_lazy('machines')

SZP/templates/delete.html
{% extends 'base.html' %}

{% block content %}
    <h2>Czy jestes pewien, że chcesz usunąć maszynę {{ object.name }}</h2>
    <form method="post">
        {% csrf_token %}
        <input type="submit" value="OK">
    </form>
{% endblock  %}

SZP/templates/form.html
{% extends 'base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Aktualizuj">
    </form>
{% endblock  %}

SZP/templates/machine_list_view.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <h2>Lista maszyn</h2>
  <table class="table table-striped table-bordered table-hover table-condensed">
    <thead>
      <tr>
        <th>nazwa</th>
        <th>producent</th>
        <th>numer seryjny</th>
        <th>zużycie energii</th>
        <th>typ</th>
        <th>położenie</th>
        <th>ciśnienie</th>
        <th>ciśnienie zbiornika</th>
        <th>schemat technologiczny</th>
        <th>zbiornik</th>
        <th>aktualizacja</th>
        <th>usuwanie</th>
      </tr>
    </thead>
    <tbody>
        {% for obj in object_list%}
        <tr class="active">
            <td>{{ obj.name }}</td>
            <td>{{ obj.vendor }}</td>
            <td>{{ obj.serial_number }}</td>
            <td>{{ obj.power_consumption }}</td>
            <td>{{ obj.get_type_display }}</td>
            <td>{{ obj.orientation }}</td>
            <td>{{ obj.pressure }}</td>
            <td>{{ obj.pressure_tank }}</td>
            <td>{{ obj.technological_schema }}</td>
            <td>{{ obj.tank }}</td>
            <td><a href="{% url 'update_machine' obj.pk%}">aktualizuj </a></td>
            <td><a href="{% url 'delete_machine' obj.pk%}">usuń</a></td>
        </tr>
    {% endfor %}
    </tbody>
  </table>
</div>



{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <title>System Zarządzania Produkcją</title>

    </head>
</head>
<body>

<div class="navigation">
    {% include 'profile.html' %}
    {% include 'buttons.html' %}
</div>
<div class="content">
    {% block content %}
    {% endblock %}
</div>


</body>
</html>

templates/buttons.html
<div class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">WebSiteName</a>
        </div>
        <ul class="nav nav-tabs" role="tablist">
            <li class="active"><a href="{% url 'index' %}">Home</a> </li>
            <li><a href="{% url 'machines' %}">Wszystkie maszyny</a></li>
            <li><a href="{% url 'create_machine' %}">Dodaj maszynę</a></li>
            <li><a href="{% url 'signup' %}">Dodaj użytkownika</a></li>
        </ul>
</div>

templates/profile.html
{% if user.is_authenticated %}
    <p>Witaj {{ user.username }}</p>
    <p><a href="{% url 'logout' %}">wyloguj</a> </p>
{% else %}
    <p><a href="{% url 'login' %}">zaloguj</a> </p>
{% endif %}